import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
import helmetGlow from './assets/horned-helmet-glow.png';

const projects = [
  { id: '01', title: 'Project Management Portal', short: 'PORTAL', category: 'FULL-STACK', subtitle: 'A structured space for serious projects.', technologies: ['React', 'Node.js', 'Express.js', 'PostgreSQL', 'Sequelize', 'JWT'], description: 'A platform for managing the final-year project workflow, including team formation, mentor assignment, project submissions, approvals, and project progress.', tone: 'portal', actions: ['VIEW PROJECT', 'GITHUB'] },
  { id: '02', title: 'SplitSnap', short: 'SPLITSNAP', category: 'AI + FULL-STACK', subtitle: 'AI receipt & expense tracker.', technologies: ['AI', 'LLM', 'Streamlit', 'Automation'], description: 'An AI-powered receipt and expense tracker that extracts receipt items and amounts and helps users split expenses between multiple people.', tone: 'split', actions: ['LIVE DEMO', 'GITHUB'] },
  { id: '03', title: 'AI Job Tracker', short: 'JOB TRACKER', category: 'AI + AUTOMATION', subtitle: 'A calmer way to find the right role.', technologies: ['n8n', 'Gemini', 'RSS', 'Google Sheets', 'LLM'], description: 'An automated workflow that collects job postings, analyzes technical requirements using AI, extracts relevant skills, and generates personalized cover letters.', tone: 'jobs', actions: ['GITHUB'] },
  { id: '04', title: 'AI News Summarizer', short: 'NEWS / AI', category: 'AI + AUTOMATION', subtitle: 'The signal, without the noise.', technologies: ['n8n', 'OpenAI', 'RSS', 'Gmail', 'LLM'], description: 'An automated workflow that collects AI and technology news, processes the articles using an LLM, generates concise summaries, and delivers the final digest through email.', tone: 'news', actions: ['GITHUB'] }
];

function Icon({ name, size = 18 }) {
  const paths = {
    code: <><path d="m8 9-3 3 3 3"/><path d="m16 9 3 3-3 3"/><path d="m14 5-4 14"/></>,
    spark: <><path d="m12 3-1.4 5.6L5 10l5.6 1.4L12 17l1.4-5.6L19 10l-5.6-1.4L12 3Z"/><path d="m5 3 .5 2L7.5 6l-2 .5L5 8l-.5-1.5L2.5 6l2-.5L5 3Z"/></>,
    database: <><ellipse cx="12" cy="5" rx="7" ry="3"/><path d="M5 5v7c0 1.7 3.1 3 7 3s7-1.3 7-3V5"/><path d="M5 12v7c0 1.7 3.1 3 7 3s7-1.3 7-3v-7"/></>,
    flow: <><rect x="3" y="3" width="6" height="6" rx="1"/><rect x="15" y="15" width="6" height="6" rx="1"/><path d="M9 6h4a3 3 0 0 1 3 3v6"/><path d="m13 13 3 3 3-3"/></>,
    flask: <><path d="M9 3h6"/><path d="M10 3v6l-5 9a2 2 0 0 0 1.8 3h10.4A2 2 0 0 0 19 18l-5-9V3"/><path d="M8 15h8"/></>,
    file: <><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6"/><path d="M8 13h8M8 17h6"/></>,
    linkedin: <><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-4 0v7h-4v-7a6 6 0 0 1 6-6Z"/><rect x="2" y="9" width="4" height="12"/><circle cx="4" cy="4" r="2"/></>,
    github: <><path d="M15 22v-3.9c.04-1-.34-1.98-1.05-2.7 3.5-.39 7.18-1.72 7.18-7.8a6.1 6.1 0 0 0-1.63-4.25A5.68 5.68 0 0 0 19.35.4S18.05 0 15 2.04a14.2 14.2 0 0 0-6 0C5.95 0 4.65.4 4.65.4a5.68 5.68 0 0 0-.15 2.95 6.1 6.1 0 0 0-1.63 4.25c0 6.07 3.67 7.4 7.18 7.8A3.73 3.73 0 0 0 9 18.28V22"/><path d="M9 19c-3 .92-4-1.5-4-1.5"/></>,
    mail: <><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></>
  };
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>
}

function ProjectArt({ project, large = false }) {
  return <div className={`project-art ${project.tone} ${large ? 'large' : ''}`} aria-hidden="true">
    <div className="art-top"><span>{project.category}</span><span>◌</span></div>
    <div className="art-center">{project.tone === 'portal' && <><i></i><i></i><i></i></>}{project.tone === 'split' && <div className="receipt"><b>splitsnap</b><span>Lunch / 04.12</span><em>₹ 1,240.00</em><small>ITEMS • 4 PEOPLE</small></div>}{project.tone === 'jobs' && <div className="job-lines"><b>Opportunity feed</b><span></span><span></span><span></span></div>}{project.tone === 'news' && <div className="news-lines"><b>THE DAILY SIGNAL</b><span>Artificial Intelligence</span><span>Technology & Tomorrow</span></div>}</div>
    <div className="art-foot"><span>{project.id} / 04</span><span>EDWIN SANTHOSH</span></div>
  </div>
}

function Hero() { return <section className="hero" id="home"><div className="hero-grid"/><img className="hero-helmet" src={helmetGlow} alt="" aria-hidden="true"/><div className="hero-content"><p className="eyebrow">FULL-STACK DEVELOPER · AI & AUTOMATION</p><h1>EDWIN<br/>SANTHOSH</h1><p className="intro">I build modern web applications, AI-powered tools,<br className="desktop"/> and automated workflows that turn ideas into<br className="desktop"/> practical solutions.</p></div><a className="go-down" href="#about">GO DOWN <b>↓</b></a></section> }
function FloatingNav(){ const [show,setShow]=useState(false); useEffect(()=>{const f=()=>setShow(scrollY>window.innerHeight*.55); addEventListener('scroll',f);f();return()=>removeEventListener('scroll',f)},[]); return <nav className={`float-nav ${show?'visible':''}`} aria-label="Primary navigation"><a href="#about">About</a><a href="#work">Work</a><a href="#journey">Journey</a><a href="#contact">Contact</a></nav> }
function About(){ const skillGroups=[['FRONTEND','HTML','CSS','JavaScript','React'],['BACKEND','Node.js','Express.js','REST APIs','JWT'],['DATABASE','PostgreSQL','MySQL','MongoDB','Sequelize'],['AI & AUTOMATION','n8n','LLM APIs','Prompt Engineering'],['TOOLS','Git','GitHub','Postman','VS Code']]; return <section id="about" className="about section"><div className="about-copy"><p className="eyebrow">01 / ABOUT</p><h2>A little context,<br/>a lot of curiosity.</h2><p>I'm Edwin, a developer focused on building modern web applications, AI-powered tools, and automated workflows.</p><p>I enjoy turning ideas into practical products while continuously learning and exploring new technologies.</p></div><div className="skills"><p className="eyebrow">SKILLS</p><div className="skill-list">{skillGroups.map(([heading,...items])=><div className="skill-group" key={heading}><b>{heading}</b><p>{items.join(' · ')}</p></div>)}</div></div></section> }
function WhatIDo(){ const data=[['01','FULL-STACK DEVELOPMENT','Building responsive web applications and REST APIs.','code'],['02','AI & AUTOMATION','Connecting AI models with real-world workflows and automation.','spark'],['03','BACKEND DEVELOPMENT','Designing APIs, authentication, databases and server-side systems.','database']]; return <section className="what section"><p className="eyebrow">02 / WHAT I DO</p><div className="services">{data.map(x=><article key={x[0]}><span>{x[0]}</span><Icon name={x[3]}/><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section> }
function Projects(){ const [focused,setFocused]=useState(null); const [current,setCurrent]=useState(0); const project=projects[current]; useEffect(()=>{const h=e=>{if(e.key==='Escape')setFocused(false); if(focused&&e.key==='ArrowRight')setCurrent(c=>(c+1)%projects.length); if(focused&&e.key==='ArrowLeft')setCurrent(c=>(c+projects.length-1)%projects.length)};addEventListener('keydown',h);return()=>removeEventListener('keydown',h)},[focused]); const move=d=>setCurrent(c=>(c+d+projects.length)%projects.length); return <section id="work" className="projects section"><div className="work-heading"><div><p className="eyebrow">03 / SELECTED WORK</p><h2>Built with intent.</h2></div><p>Four projects at the intersection<br className="desktop"/> of product, code and intelligence.</p></div><div className="project-row">{projects.map((p,i)=><button className="project-tile" key={p.id} onClick={()=>{setCurrent(i);setFocused(true)}}><ProjectArt project={p}/><span className="tile-meta"><em>{p.id}</em><b>{p.short}</b><i>OPEN PROJECT ↗</i></span></button>)}</div>{focused && <div className="project-focus" role="dialog" aria-modal="true" aria-label={`${project.title} project details`} onMouseDown={e=>{if(e.target===e.currentTarget)setFocused(false)}}><div className={`focus-backdrop ${project.tone}`}></div><button className="edge-control prev" onClick={()=>move(-1)} aria-label="Previous project">←</button><article className="focus-card"><button className="close" onClick={()=>setFocused(false)} aria-label="Close project">×</button><ProjectArt project={project} large/><div className="focus-copy"><p className="eyebrow">{project.id} / 04 · {project.category}</p><h3>{project.title}</h3><h4>{project.subtitle}</h4><p>{project.description}</p><div className="tags">{project.technologies.map(t=><span key={t}>{t}</span>)}</div><div className="project-actions">{project.actions.map(a=><a href="#contact" key={a}>{a} <b>↗</b></a>)}</div></div></article><button className="edge-control next" onClick={()=>move(1)} aria-label="Next project">→</button><p className="focus-counter">{project.id} / 04</p></div>}</section> }
function Automation(){return <section className="automation section"><div><p className="eyebrow">04 / AI & AUTOMATION</p><h2>Systems that<br/>keep moving.</h2><p>I design workflows that collect, understand and deliver useful information—without making people chase it.</p></div><div className="flow"><span>DATA</span><i>↓</i><span>AUTOMATE <Icon name="flow"/></span><i>↓</i><span>AI <Icon name="spark"/></span><i>↓</i><span>PROCESS</span><i>↓</i><span>OUTPUT</span></div></section>}
function Journey(){const items=[['2022','Started B.E. Computer Science Engineering (Cyber Security)'],['2024','Focused more deeply on full-stack development.'],['2025','Built the Project Management Portal.'],['2026','Built AI-powered applications and n8n automation workflows.'],['NOW','Looking for opportunities to build, learn and grow as a software developer.']];return <><section id="journey" className="journey section"><p className="eyebrow">05 / MY JOURNEY</p><h2>In progress.</h2><div className="timeline">{items.map(x=><article key={x[0]}><b>{x[0]}</b><i></i><p>{x[1]}</p></article>)}</div></section><section className="education section"><p className="eyebrow">EDUCATION</p><div><h3>B.E. Computer Science Engineering<br/><span>(Cyber Security)</span></h3><p>Sathyabama University<br/>2022 — 2026</p></div><div><h3>Higher Secondary Education</h3><p>2020 — 2022</p></div></section></>}
function Contact(){return <><section className="resume section"><p className="eyebrow">06 / RESUME</p><h2>Want to know more?</h2><p>Take a look at my resume.</p><div className="project-actions"><a href="#contact"><Icon name="file" size={14}/> VIEW RESUME <b>↗</b></a><a href="#contact"><Icon name="file" size={14}/> DOWNLOAD PDF <b>↓</b></a></div></section><section id="contact" className="contact"><div><p className="eyebrow">07 / CONTACT</p><h2>LET'S BUILD<br/><i>SOMETHING.</i></h2><p>Have an opportunity, idea,<br/>or just want to connect?</p><div className="contact-links"><a href="https://www.linkedin.com" target="_blank"><Icon name="linkedin"/>LinkedIn ↗</a><a href="https://github.com" target="_blank"><Icon name="github"/>GitHub ↗</a><a href="mailto:hello@example.com"><Icon name="mail"/>Email ↗</a></div></div><footer><b>EDWIN SANTOSH</b><span>Full-Stack Developer · AI & Automation</span><span>© 2026</span></footer></section></>}
function App(){return <><FloatingNav/><Hero/><main><About/><WhatIDo/><Projects/><Automation/><section className="experiments section"><p className="eyebrow">OTHER EXPERIMENTS</p><article><span>01</span><div><h3><Icon name="flask"/>Web Proxy</h3><p>A backend experiment exploring web requests and browser automation.</p></div><p>Node.js · Puppeteer</p><a href="#contact">EXPLORE ↗</a></article></section><Journey/><Contact/></main></>};
createRoot(document.getElementById('root')).render(<App/>);
